version: 2.1

orbs:
 ganta-git:ganat/git@1.2.0
 
jobs:
 build:
   docker:
     - image: circleci/android:api-28
   resource_class: xlarge
   steps:
     - ganta-git/shallow-clone-checkout
     - run: echo $CIRCLR_JOB
     - run:
         name: Single command - echo
         command: echo $CIRCLE_USERNAME
     - run:
         name: Muti-line commands - echo & echo
         command: |
           echo $CIRCLR_REPOSITORY_URL
           echo $CIRCLE_BRANCH
